# -*- coding: utf-8 -*-
"""LogisticRegression.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z-UmGmbTjtUapkrbagO3QBk-82g6Rk4S
"""

import pandas as pd

file=pd.read_csv("/content/breast-cancer.csv")
file

file.info()



input = file[["radius_mean", "texture_mean", "perimeter_mean"]]
output = file["diagnosis"]

from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(input , output)

model.predict([[17.99,1038,122.8]])